import React, { useEffect, useMemo, useRef, useState } from "react";

/*
  Dictionnaire Franglais
  Tier A + Tier 2
  Data embedded exactly as-is from the book-form PDF
*/

const DATA = {
  tiers: {
    A: [
      { en: "art", fr: "art" },
      { en: "audio", fr: "audio" },
      { en: "ballet", fr: "ballet" },
      { en: "bar", fr: "bar" },
      { en: "camera", fr: "camera" },
      { en: "cinema", fr: "cinema" },
      { en: "climate", fr: "climate" },
      { en: "crisis", fr: "crisis" },
      { en: "culture", fr: "culture" },
      { en: "design", fr: "design" },
      { en: "detail", fr: "detail" },
      { en: "document", fr: "document" },
      { en: "drama", fr: "drama" },
      { en: "error", fr: "error" },
      { en: "festival", fr: "festival" },
      { en: "final", fr: "final" },
      { en: "global", fr: "global" },
      { en: "hotel", fr: "hotel" },
      { en: "image", fr: "image" },
      { en: "internet", fr: "internet" },
      { en: "menu", fr: "menu" },
      { en: "music", fr: "music" },
      { en: "national", fr: "national" },
      { en: "normal", fr: "normal" },
      { en: "option", fr: "option" },
      { en: "original", fr: "original" },
      { en: "panic", fr: "panic" },
      { en: "photo", fr: "photo" },
      { en: "radio", fr: "radio" },
      { en: "region", fr: "region" },
      { en: "restaurant", fr: "restaurant" },
      { en: "scene", fr: "scene" },
      { en: "solution", fr: "solution" },
      { en: "style", fr: "style" },
      { en: "taxi", fr: "taxi" },
      { en: "theatre", fr: "theatre" },
      { en: "video", fr: "video" }
    ],

    2: [
      { en: "abandon", fr: "abandonner" },
      { en: "absolute", fr: "absolu" },
      { en: "absolutely", fr: "absolument" },
      { en: "academic", fr: "academique" },
      { en: "accept", fr: "accepter" },
      { en: "accident", fr: "accident" },
      { en: "active", fr: "actif" },
      { en: "activity", fr: "activite" },
      { en: "actual", fr: "actuel" },
      { en: "actually", fr: "actuellement" },
      { en: "administration", fr: "administration" },
      { en: "admit", fr: "admettre" },
      { en: "adult", fr: "adulte" },
      { en: "advance", fr: "avance" },
      { en: "advantage", fr: "avantage" },
      { en: "affair", fr: "affaire" },
      { en: "affect", fr: "affecter" },
      { en: "affirmative", fr: "affirmatif" },
      { en: "aggressive", fr: "agressif" },
      { en: "alarm", fr: "alarme" },
      { en: "alternative", fr: "alternative" },
      { en: "ambition", fr: "ambition" },
      { en: "analysis", fr: "analyse" },
      { en: "announce", fr: "annoncer" },
      { en: "anxiety", fr: "anxiete" },
      { en: "apparent", fr: "apparent" },
      { en: "apparently", fr: "apparemment" },
      { en: "application", fr: "application" },
      { en: "argument", fr: "argument" },
      { en: "artificial", fr: "artificiel" },
      { en: "assist", fr: "assister" },
      { en: "association", fr: "association" },
      { en: "assume", fr: "assumer" },
      { en: "atmosphere", fr: "atmosphere" },
      { en: "automatic", fr: "automatique" },
      { en: "balance", fr: "balance" },
      { en: "basic", fr: "basique" },
      { en: "benefit", fr: "benefice" },
      { en: "brilliant", fr: "brillant" },
      { en: "capital", fr: "capital" },
      { en: "category", fr: "categorie" },
      { en: "celebrate", fr: "celebrer" },
      { en: "central", fr: "central" },
      { en: "certain", fr: "certain" },
      { en: "classic", fr: "classique" },
      { en: "collective", fr: "collectif" },
      { en: "comfort", fr: "confort" },
      { en: "comment", fr: "commentaire" },
      { en: "communicate", fr: "communiquer" },
      { en: "complex", fr: "complexe" },
      { en: "concept", fr: "concept" },
      { en: "conclusion", fr: "conclusion" },
      { en: "confidence", fr: "confiance" },
      { en: "conflict", fr: "conflit" },
      { en: "consequence", fr: "consequence" },
      { en: "consider", fr: "considerer" },
      { en: "constant", fr: "constant" },
      { en: "construct", fr: "construire" },
      { en: "contact", fr: "contact" },
      { en: "context", fr: "contexte" },
